# Generated by Django 5.2.2 on 2025-07-09 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_discription_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description2',
            field=models.TextField(blank=True),
        ),
    ]
